#!/usr/bin/env python
# encoding: utf-8

import psutil


def is_mysql_is_running():
    return len([x for x in psutil.process_iter() if x.name().lower() == "mysqld"]) > 0

if __name__ == '__main__':
    print is_mysql_is_running()
